name: NodeJs

on:
  push:
    branches:
      - master

jobs:
  Build-Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Build
        run: npm install

      - name: Test
        run: npm test
      - name: Cache Dependencies
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key:  ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-1
          path: |
            package*

      - name: Deploy
        run: echo "code is deployed"
