name:  NodeJs
 
on:
  push:
     branch: master
 
permissions:
   security-events: write
   issues: write
   actions: read
   contents: read
 
jobs:
  Build-Test:
    runs-on:  ubuntu-latest
    steps:
      - name:  Checkout Code
        uses:  actions/checkout@v7
 
      - name: Set up Nodejs
        uses: actions/setup-node@v6
        with:
          node-version: '24'
 
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
 
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3
 
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
 
      - name: Build
        run: npm install
 
      - name: test
        run: npm test
 
      - name: Artifact upload
        uses: actions/upload-artifact@v7
        with:
          name: artifact-1
          path: |
             package*
 
      - name: Deploy
        run: echo "code is deployed"
