name: project2

on:
  push:
    branches:
      - 'master'
      - 'dev/**'
    paths:
      - "src/**"
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build application
        run: npm run build

      - name: Artifact upload
        uses: actions/upload-artifact@v4
        with:
          name: artifact-1
          path: |
             package*

      - name: Deploy
        run: echo "Deploying to production server..."

  info:
    runs-on: ubuntu-latest

    steps:
      - name: Output GitHub context
        run: echo '${{ toJson(github) }}'
