jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/develop' # Only run for the develop branch
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to Staging..."

  deploy-production:
    if: github.ref == 'refs/heads/main' # Only run for the main branch
    environment: production
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to Production..."
